import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';
import { PipelineRunner } from '../execution/PipelineRunner';
import { Logger } from '../utils/logger';
import { createSpinner } from '../utils/ProgressBar';
import { DiffChecker, DiffResult } from './DiffChecker';
import { TaggedExchangeLogEntry } from './ExchangeLog';
import { HTMLDiffReporter } from './HTMLDiffReporter';

export interface DebugReplayOptions {
  scriptPath: string;
  recordingLogPath?: string;
  outHtmlPath: string;
  replayLogPath?: string;
  vus?: number;
  iterations?: number;
}

export interface DebugReplayResult {
  htmlReportPath: string;
  replayLogPath: string;
  results: DiffResult[];
  recordingLogPath?: string;
}

export class ReplayRunner {
  private static readonly REPLAY_PREFIX = '[k6-perf][replay-log] ';

  /**
   * Run a k6 script in debug mode, capture replay logs, compare them to the recording log,
   * and generate an HTML diff report automatically.
   */
  static async runDebug(options: DebugReplayOptions): Promise<DebugReplayResult> {
    Logger.detail(`Script  : ${options.scriptPath}`);
    Logger.detail(`Recording: ${options.recordingLogPath ?? 'none (replay-only mode)'}`);

    const absScriptPath = path.resolve(options.scriptPath);
    const absRecordingLogPath = options.recordingLogPath
      ? path.resolve(options.recordingLogPath)
      : undefined;
    const absHtmlPath = path.resolve(options.outHtmlPath);
    const absReplayLogPath = path.resolve(
      options.replayLogPath ?? this.defaultReplayLogPath(absHtmlPath),
    );
    const vus = options.vus ?? 1;
    const iterations = options.iterations ?? 1;

    if (!fs.existsSync(absScriptPath)) {
      throw new Error(`[ReplayRunner] Script not found: ${absScriptPath}`);
    }
    if (absRecordingLogPath && !fs.existsSync(absRecordingLogPath)) {
      Logger.detail(`Recording log not found, replay-only mode`);
    }

    const execSpinner = createSpinner('Executing k6 debug run');
    execSpinner.start();
    const runResult = PipelineRunner.execute({
      scriptPath: absScriptPath,
      k6Options: {
        scenarios: {
          debug_replay: {
            executor: 'shared-iterations',
            vus,
            iterations,
          }
        }
      },
      env: { K6_PERF_DEBUG: 'true' },
      captureOutput: true,
    });
    execSpinner.done('k6 debug execution complete');

    const extractSpinner = createSpinner('Extracting replay entries');
    extractSpinner.start();
    const replayEntries = await this.extractReplayEntries(runResult);
    this.writeJson(absReplayLogPath, replayEntries);
    extractSpinner.done(`Extracted ${replayEntries.length} replay entries`);

    // Extract k6 runtime errors for the HTML report
    const k6Errors = this.extractK6Errors(runResult);

    if (replayEntries.length === 0) {
      if (runResult.status !== 0) {
        throw new Error(
          `[ReplayRunner] k6 debug execution failed before replay logs were captured. ` +
          `Inspect the k6 error output above for the exact cause.`,
        );
      }
      throw new Error(
        `[ReplayRunner] No replay-log entries were captured from script output. ` +
        `Make sure the script was generated by the framework or emits [k6-perf][replay-log] lines.`,
      );
    }

    const reportSpinner = createSpinner('Generating diff report');
    reportSpinner.start();
    const recordingEntries = absRecordingLogPath && fs.existsSync(absRecordingLogPath)
      ? this.readRecordingLog(absRecordingLogPath)
      : [];
    const missingRecordingWarning =
      recordingEntries.length === 0
        ? `[ReplayRunner] Recording log not found. Report shows replay data only for script ${absScriptPath}.`
        : undefined;
    const diffResults = DiffChecker.compareTaggedLogs(recordingEntries, replayEntries, {
      missingRecordingWarning,
    });
    HTMLDiffReporter.generateReport(diffResults, absHtmlPath, { k6Errors });
    reportSpinner.done('Diff report generated');

    PipelineRunner.ensureSuccess(runResult);

    return {
      htmlReportPath: absHtmlPath,
      replayLogPath: absReplayLogPath,
      results: diffResults,
      recordingLogPath: absRecordingLogPath,
    };
  }

  private static async extractReplayEntries(runResult: { stdout?: string; stderr?: string; stdoutPath?: string; stderrPath?: string }): Promise<TaggedExchangeLogEntry[]> {
    const entries: TaggedExchangeLogEntry[] = [];
    this.collectReplayEntriesFromText(runResult.stdout, entries);
    this.collectReplayEntriesFromText(runResult.stderr, entries);

    if (runResult.stdoutPath && fs.existsSync(runResult.stdoutPath)) {
      await this.collectReplayEntriesFromFile(runResult.stdoutPath, entries);
    }
    if (runResult.stderrPath && fs.existsSync(runResult.stderrPath)) {
      await this.collectReplayEntriesFromFile(runResult.stderrPath, entries);
    }

    return entries;
  }

  private static async collectReplayEntriesFromFile(filePath: string, entries: TaggedExchangeLogEntry[]): Promise<void> {
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const reader = readline.createInterface({
      input: stream,
      crlfDelay: Infinity,
    });

    try {
      for await (const line of reader) {
        this.collectReplayEntryFromLine(line, entries);
      }
    } finally {
      reader.close();
      stream.close();
    }
  }

  private static collectReplayEntriesFromText(output: string | undefined, entries: TaggedExchangeLogEntry[]): void {
    if (!output) return;

    const lines = output.split(/\r?\n/);
    for (const line of lines) {
      this.collectReplayEntryFromLine(line, entries);
    }
  }

  private static collectReplayEntryFromLine(line: string, entries: TaggedExchangeLogEntry[]): void {
    const jsonPayload = this.extractReplayPayload(line);
    if (!jsonPayload) return;

    try {
      entries.push(this.parseReplayEntry(jsonPayload));
    } catch (error) {
      Logger.warn(`[ReplayRunner] Failed to parse replay log line`, {
        error: (error as Error).message,
        preview: jsonPayload.slice(0, 500),
      });
    }
  }

  private static extractReplayPayload(line: string): string | null {
    const consoleMatch = line.match(/msg="((?:\\.|[^"])*)"\s+source=console/);
    if (consoleMatch) {
      let rawMessage: string;
      try {
        rawMessage = JSON.parse(`"${consoleMatch[1]}"`) as string;
      } catch {
        rawMessage = consoleMatch[1].replace(/\\"/g, '"');
      }

      if (!rawMessage.includes(this.REPLAY_PREFIX)) {
        return null;
      }

      const prefixIndex = rawMessage.indexOf(this.REPLAY_PREFIX);
      return rawMessage.slice(prefixIndex + this.REPLAY_PREFIX.length).trim();
    }

    const prefixIndex = line.indexOf(this.REPLAY_PREFIX);
    if (prefixIndex === -1) return null;

    return line.slice(prefixIndex + this.REPLAY_PREFIX.length).trim();
  }

  private static parseReplayEntry(jsonPayload: string): TaggedExchangeLogEntry {
    return JSON.parse(jsonPayload) as TaggedExchangeLogEntry;
  }

  private static readRecordingLog(filePath: string): TaggedExchangeLogEntry[] {
    const raw = fs.readFileSync(filePath, 'utf-8');
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) {
      throw new Error(`[ReplayRunner] Recording log must be a JSON array: ${filePath}`);
    }
    return (parsed as TaggedExchangeLogEntry[]).map((entry) => this.normalizeRecordingEntry(entry));
  }

  private static readonly STATIC_EXT_RE = /\.(?:png|jpe?g|gif|svg|ico|webp|avif|bmp|tiff?|woff2?|ttf|otf|eot|mp[34]|webm|ogg|flac|wav|zip|gz|br|pdf)(?:[?#]|$)/i;

  private static normalizeRecordingEntry(entry: TaggedExchangeLogEntry): TaggedExchangeLogEntry {
    const isBinaryUrl = this.STATIC_EXT_RE.test(entry.request?.url ?? '');
    return {
      ...entry,
      request: {
        ...entry.request,
        body: this.decodeBodyIfNeeded(entry.request.body),
      },
      response: {
        ...entry.response,
        body: isBinaryUrl ? '[binary: static asset]' : this.decodeBodyIfNeeded(entry.response.body),
      },
    };
  }

  private static decodeBodyIfNeeded(value?: string): string | undefined {
    if (!value) return value;
    if (!this.looksLikeBase64(value)) return value;

    try {
      const decoded = Buffer.from(value, 'base64').toString('utf-8');
      if (this.looksReadable(decoded)) {
        return decoded;
      }
    } catch {
      // keep original body if decode fails
    }

    return value;
  }

  private static looksLikeBase64(value: string): boolean {
    const compact = value.replace(/\s+/g, '');
    if (compact.length < 32 || compact.length % 4 !== 0) return false;
    return /^[A-Za-z0-9+/=]+$/.test(compact);
  }

  private static looksReadable(value: string): boolean {
    const trimmed = value.trim();
    return (
      trimmed.startsWith('<') ||
      trimmed.startsWith('{') ||
      trimmed.startsWith('[') ||
      /[\r\n\t ]/.test(value) ||
      /<!DOCTYPE html>/i.test(value)
    );
  }

  private static writeJson(filePath: string, data: unknown): void {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
  }

  /**
   * Extract k6 runtime error messages from captured stdout/stderr.
   * k6 errors appear as `level=error msg="..."` or `ERRO[xxxx] ...` lines.
   */
  private static extractK6Errors(runResult: { stdout?: string; stderr?: string; stdoutPath?: string; stderrPath?: string }): string[] {
    const errors: string[] = [];
    const seen = new Set<string>();

    const processLine = (line: string) => {
      // k6 logfmt: level=error msg="GoError: ..." or level=error msg="..."
      const logfmtMatch = line.match(/level=error\s+msg="((?:\\.|[^"])*)"/);
      if (logfmtMatch) {
        let msg: string;
        try {
          msg = JSON.parse(`"${logfmtMatch[1]}"`) as string;
        } catch {
          msg = logfmtMatch[1].replace(/\\"/g, '"');
        }
        if (!seen.has(msg)) {
          seen.add(msg);
          errors.push(msg);
        }
        return;
      }
      // k6 ERRO prefix: ERRO[0042] GoError: ...
      const erroMatch = line.match(/ERRO\[\d+\]\s+(.*)/);
      if (erroMatch) {
        const msg = erroMatch[1].trim();
        if (!seen.has(msg)) {
          seen.add(msg);
          errors.push(msg);
        }
      }
    };

    const processText = (text?: string) => {
      if (!text) return;
      text.split(/\r?\n/).forEach(processLine);
    };

    processText(runResult.stdout);
    processText(runResult.stderr);

    // Also read from file paths if they exist
    if (runResult.stdoutPath && fs.existsSync(runResult.stdoutPath)) {
      processText(fs.readFileSync(runResult.stdoutPath, 'utf-8'));
    }
    if (runResult.stderrPath && fs.existsSync(runResult.stderrPath)) {
      processText(fs.readFileSync(runResult.stderrPath, 'utf-8'));
    }

    return errors;
  }

  private static defaultReplayLogPath(htmlPath: string): string {
    const parsed = path.parse(htmlPath);
    return path.join(parsed.dir, `${parsed.name}.replay-log.json`);
  }
}
