// Generated by Grafana k6 Studio (1.12.0) on 2026-04-01T22:07:39.004Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";
import csv from "k6/experimental/csv";
import fs from "k6/experimental/fs";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

const FILES = {
  userdetails: await csv.parse(await fs.open("../Data/userdetails.csv"), {
    asObjects: true,
  }),

  pet: await csv.parse(await fs.open("../Data/pet.csv"), { asObjects: true }),
};

function getUniqueItem(array) {
  return array[execution.scenario.iterationInTest % array.length];
}

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("t01_launch", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("t02_login", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "upgrade-insecure-requests": `1`,
        "sec-purpose": `prefetch`,
        "sec-speculation-tags": `null`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/account/signonForm`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 503": (r) => r.status === 503 });

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/account/signonForm`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://jpetstore.aspectran.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/account/signonForm`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
      redirects: 0,
    };

    url = http.url`https://jpetstore.aspectran.com/account/signon`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"referer":"","username":"${getUniqueItem(FILES["userdetails"])["p_username"]}","password":"${getUniqueItem(FILES["userdetails"])["p_password"]}"}`,
      ),
      params,
    );

    check(resp, { "status equals 302": (r) => r.status === 302 });

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        referer: `https://jpetstore.aspectran.com/account/signonForm`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("search_animal", function () {
    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/catalog/searchProducts?keyword=${getUniqueItem(FILES["pet"])["p_pet"]}`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    regex = new RegExp('href="/products/[^"]+">(.*?)</a></strong>');
    match = resp.body.match(regex);
    if (match) {
      correlation_vars["correlation_0"] = match[1];
    }
  });
  sleep(1);
  group("select product", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "upgrade-insecure-requests": `1`,
        "sec-purpose": `prefetch`,
        "sec-speculation-tags": `null`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/catalog/searchProducts?keyword=dog`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/products/${correlation_vars["correlation_0"]}`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 503": (r) => r.status === 503 });

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/catalog/searchProducts?keyword=dog`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/products/${correlation_vars["correlation_0"]}`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("add to cart", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "upgrade-insecure-requests": `1`,
        "sec-purpose": `prefetch`,
        "sec-speculation-tags": `null`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/products/${correlation_vars["correlation_0"]}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/cart/addItemToCart?itemId=EST-6`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 503": (r) => r.status === 503 });

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/products/${correlation_vars["correlation_0"]}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
      redirects: 0,
    };

    url = http.url`https://jpetstore.aspectran.com/cart/addItemToCart?itemId=EST-6`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 302": (r) => r.status === 302 });

    params = {
      headers: {
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        referer: `https://jpetstore.aspectran.com/products/${correlation_vars["correlation_0"]}`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/cart/viewCart`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("increase quantity to 2 and proceed to checkout", function () {
    params = {
      headers: {
        "sec-ch-ua-platform": `"Windows"`,
        "hx-target": `jpetstore-content`,
        "hx-current-url": `https://jpetstore.aspectran.com/cart/viewCart`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "hx-request": `true`,
        "content-type": `application/x-www-form-urlencoded`,
        accept: `*/*`,
        origin: `https://jpetstore.aspectran.com`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `cors`,
        "sec-fetch-dest": `empty`,
        referer: `https://jpetstore.aspectran.com/cart/viewCart`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/cart/updateCartQuantities`;
    resp = http.request("POST", url, JSON.parse(`{"EST-6":"2"}`), params);

    check(resp, { "status equals 200": (r) => r.status === 200 });

    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "upgrade-insecure-requests": `1`,
        "sec-purpose": `prefetch`,
        "sec-speculation-tags": `null`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/cart/viewCart`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/order/newOrderForm`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 503": (r) => r.status === 503 });

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/cart/viewCart`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/order/newOrderForm`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("click continue", function () {
    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://jpetstore.aspectran.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/order/newOrderForm`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/order/newOrder`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(
        `{"paymentForm":"true","billingForm":"true","cardType":"Visa","creditCard":"999999999999999","expiryDate":"12/2019","billToFirstName":"UpdatedFirst","billToLastName":"UpdatedLast","billAddress1":"New Address 1","billAddress2":"New Address 2","billCity":"NewCity","billState":"NewState","billZip":"54321","billCountry":"Philippines"}`,
      ),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("click confirm", function () {
    params = {
      headers: {
        "cache-control": `max-age=0`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        origin: `https://jpetstore.aspectran.com`,
        "content-type": `application/x-www-form-urlencoded`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/order/newOrder`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
      redirects: 0,
    };

    url = http.url`https://jpetstore.aspectran.com/order/submitOrder`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(`{"confirmed":"true"}`),
      params,
    );

    check(resp, { "status equals 302": (r) => r.status === 302 });

    regex = new RegExp("orderId=(.*?)&submitted");
    match = resp.headers["Location"].match(regex);
    if (match) {
      correlation_vars["correlation_1"] = match[1];
    }

    params = {
      headers: {
        "cache-control": `max-age=0`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        referer: `https://jpetstore.aspectran.com/order/newOrder`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/order/viewOrder?orderId=${correlation_vars["correlation_1"]}&submitted=true`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
  group("logout", function () {
    params = {
      headers: {
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "upgrade-insecure-requests": `1`,
        "sec-purpose": `prefetch`,
        "sec-speculation-tags": `null`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "sec-fetch-site": `none`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/order/viewOrder?orderId=${correlation_vars["correlation_1"]}&submitted=true`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=1, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/account/signoff`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 503": (r) => r.status === 503 });

    params = {
      headers: {
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        referer: `https://jpetstore.aspectran.com/order/viewOrder?orderId=${correlation_vars["correlation_1"]}&submitted=true`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
      redirects: 0,
    };

    url = http.url`https://jpetstore.aspectran.com/account/signoff`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 302": (r) => r.status === 302 });

    params = {
      headers: {
        "upgrade-insecure-requests": `1`,
        accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        "sec-fetch-site": `same-origin`,
        "sec-fetch-mode": `navigate`,
        "sec-fetch-user": `?1`,
        "sec-fetch-dest": `document`,
        "sec-ch-ua": `"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"`,
        "sec-ch-ua-mobile": `?0`,
        "sec-ch-ua-platform": `"Windows"`,
        referer: `https://jpetstore.aspectran.com/order/viewOrder?orderId=${correlation_vars["correlation_1"]}&submitted=true`,
        "accept-encoding": `gzip, deflate, br, zstd`,
        "accept-language": `en-US,en;q=0.9`,
        priority: `u=0, i`,
      },
      cookies: {},
    };

    url = http.url`https://jpetstore.aspectran.com/`;
    resp = http.request("GET", url, null, params);

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
